### ISSUE TITLE
Redundant parameters

### ISSUE THREAD

**Issue by base64bits** [24u/fmRESTor#3]
Thanks for this awesome library, we have one concern about it.

The $fmDataSource array already has some of the variables that are needed for the db connection, but they are also required in the other parameters, seems like only $layout and $host is missing from the array, by adding that to the array wouldn't be better to just pass $options, $fmDataSource?

$fmDataSource = array(
    array(
        "database" => "fmRESTorBUDY",
        "username" => "budy",
        "password" => "budy123456"
    )
);

$fm = new fmRESTor($host, $database, $layout, $user, $password, $options, $fmDataSource);

**Comment by filip24u** [comment]
Thanks for the comment. In fact the $fmDataSource parameter is meant for providing **additional** data sources, i.e. if you use a separation model and the current layout needs to access data from external data sources.

**Comment by base64bits** [comment]
Got it, thanks!
