### ISSUE TITLE
runScript

### ISSUE THREAD

**Issue by rockycastaneda** [24u/fmRESTor#6]
will version 17 ever support runScript?  is there an alternative to running scripts on v17 of Filemaker?

**Comment by filip24u** [comment]
Hello,

function runScript in fmRESTor is supported only for FileMaker 18, but you can run FileMaker script in FileMaker 17 for example via function createRecord.

You can create record for example in some "log" table, where you insert only timestamp into your custom field and in call you can set optional parameters for running a FileMaker Script.

Example:

```
$newRecord = array(
    "fieldData" => array(
    "yourNameField" => date(),
),
"script" => "Log request - Script Name",
"script.param" => "String parameters for script"
);

$response = $fm->createRecord($newRecord);
```
