### ISSUE TITLE
Constant not being recognized

### ISSUE THREAD

**Issue by nexgen** [24u/fmRESTor#8]
The constant like: LOG_TYPE_DEBUG is not being recognized.

I'm using this code without using composer like this:
`
session_start();
require_once __DIR__ . '/src/fmRESTor.php';
use fmRESTor\fmRESTor;
$fm = new fmRESTor($host, $database, $layout, $user, $password, $options, $fmExternalSource);
`

**Comment by filip24u** [comment]
Hello nexgen,

Thank you for reporting the bug, I really appreciate it. I'm sorry for the late reply. The reported bug has been fixed in version 19.x. (this new version has been released, before few days).

Have a nice day,
Filip
